// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5NbOhhD1NBDXrgdinIpUME30Nyp66AUg',
    appId: '1:135210812450:web:75df190f1e90de4e7fb67b',
    messagingSenderId: '135210812450',
    projectId: 'ispgayaapp',
    authDomain: 'ispgayaapp.firebaseapp.com',
    storageBucket: 'ispgayaapp.appspot.com',
    measurementId: 'G-J41B8DDG17',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHAbVBNn_nCJZr6ryQyRNVeId5dOAWqT8',
    appId: '1:135210812450:android:6659c97dead35f357fb67b',
    messagingSenderId: '135210812450',
    projectId: 'ispgayaapp',
    storageBucket: 'ispgayaapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOuQ0kaX53jIJowSQYbZjvdZUgfMpbY7g',
    appId: '1:135210812450:ios:e8a01d53ab1e11507fb67b',
    messagingSenderId: '135210812450',
    projectId: 'ispgayaapp',
    storageBucket: 'ispgayaapp.appspot.com',
    iosBundleId: 'com.example.projetoIspgaya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOuQ0kaX53jIJowSQYbZjvdZUgfMpbY7g',
    appId: '1:135210812450:ios:e8a01d53ab1e11507fb67b',
    messagingSenderId: '135210812450',
    projectId: 'ispgayaapp',
    storageBucket: 'ispgayaapp.appspot.com',
    iosBundleId: 'com.example.projetoIspgaya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5NbOhhD1NBDXrgdinIpUME30Nyp66AUg',
    appId: '1:135210812450:web:fb2df5ac5e03cc967fb67b',
    messagingSenderId: '135210812450',
    projectId: 'ispgayaapp',
    authDomain: 'ispgayaapp.firebaseapp.com',
    storageBucket: 'ispgayaapp.appspot.com',
    measurementId: 'G-ZKYPHRL2BM',
  );
}
