// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5NbOhhD1NBDXrgdinIpUME30Nyp66AUg',
    appId: '1:135210812450:web:7f9584be4be865a37fb67b',
    messagingSenderId: '135210812450',
    projectId: 'ispgayaapp',
    authDomain: 'ispgayaapp.firebaseapp.com',
    storageBucket: 'ispgayaapp.appspot.com',
    measurementId: 'G-4W5H51W9BZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHAbVBNn_nCJZr6ryQyRNVeId5dOAWqT8',
    appId: '1:135210812450:android:5a19e229f92697277fb67b',
    messagingSenderId: '135210812450',
    projectId: 'ispgayaapp',
    storageBucket: 'ispgayaapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOuQ0kaX53jIJowSQYbZjvdZUgfMpbY7g',
    appId: '1:135210812450:ios:e63d7e394c720ee57fb67b',
    messagingSenderId: '135210812450',
    projectId: 'ispgayaapp',
    storageBucket: 'ispgayaapp.appspot.com',
    iosBundleId: 'com.example.projetoIspgaya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOuQ0kaX53jIJowSQYbZjvdZUgfMpbY7g',
    appId: '1:135210812450:ios:e63d7e394c720ee57fb67b',
    messagingSenderId: '135210812450',
    projectId: 'ispgayaapp',
    storageBucket: 'ispgayaapp.appspot.com',
    iosBundleId: 'com.example.projetoIspgaya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5NbOhhD1NBDXrgdinIpUME30Nyp66AUg',
    appId: '1:135210812450:web:6c1c3a89ce1b67e17fb67b',
    messagingSenderId: '135210812450',
    projectId: 'ispgayaapp',
    authDomain: 'ispgayaapp.firebaseapp.com',
    storageBucket: 'ispgayaapp.appspot.com',
    measurementId: 'G-WL5YZ3QJS4',
  );

}